name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2git init


      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Deploy
        uses: actions/deploy-pages@v1
        with:
          branch: gh-pages
          folder: .
