name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.6  # Korrigierte GitHub Pages Action
        with:
          branch: gh-pages  # GitHub Pages Branch
          folder: ./        # Der Ordner, der veröffentlicht werden soll
